winget install 7zip.7zip
winget install Lexikos.AutoHotkey
winget install voidtools.Everything
winget install File-New-Project.EarTrumpet
winget install Microsoft.VisualStudioCode
winget install VideoLAN.VLC
winget install WinDirStat.WinDirStat
winget install Microsoft.WindowsTerminal
choco install teracopy