[terminal]
[terminal.shell]
program               = "/usr/bin/fish"
args                  = ["-c", "zellij attach --create main"]

[scrolling]
history               = 65535

[font]
normal                = { family = "Hasklug Nerd Font Mono", style = "Regular" }
bold                  = { family = "Hasklug Nerd Font Mono", style = "Bold" }
italic                = { family = "Hasklug Nerd Font Mono", style = "Italic" }
bold_italic           = { family = "Hasklug Nerd Font Mono", style = "Bold Italic" }
size                  = 12.0
